ccp_neutron_plugin_agent: "openvswitch"
ccp_misc_dir: /root/ccp
ccp_conf: /root/ccp/ccp.yaml
ccp_builder_push: "True"
ccp_registry_address: "127.0.0.1:31500"
ccp_images_namespace: "ccp"
ccp_namespace: "ccp"
ccp_public_interface: "eth1"
ccp_private_interface: "eth2"
ccp_neutron_external_interface: "eth3"
ccp_neutron_logging_debug: "false"
ccp_calico_etcd_host: "etcd"
ccp_calico_etcd_port: "2379"

ccp_nodes:
  - name: "node1"
    role: controller
  - name: "node[2-3]"
    role: compute

ccp_roles:
  controller:
    calico:
      - controller
      - lma
      - lma-controller
      - neutron-agents
    openvswitch:
      - controller
      - lma
      - lma-controller
      - openvswitch
      - neutron-agents
  compute:
    calico:
      - compute
      - lma
      - calico
    openvswitch:
      - compute
      - lma
      - openvswitch

neutron_agents:
    calico:
      - neutron-metadata-agent
    openvswitch:
      - neutron-metadata-agent
      - neutron-dhcp-agent
      - neutron-l3-agent

calico_services:
  - calico-dhcp-agent
  - calico-felix
