- name: Fetch CCP images
  shell: ccp --config-file={{ ccp_conf }} fetch
  run_once: true
  when: ccp_fetch|default(true)

- name: Patch projects
  shell: git fetch "{{ ccp_gerrit_base }}/{{ item.repo }}" {{ item.refspec }} && git cherry-pick FETCH_HEAD
  run_once: true
  with_items: "{{ ccp_gerrit_reviews }}"
  when: ccp_gerrit_reviews is defined

- name: Build CCP images
  shell: ccp --config-file={{ ccp_conf }} build
  run_once: true
  when: ccp_build|default(true)
