- name: Fetch CCP images
  shell: ccp --config-file={{ ccp_conf }} fetch
  run_once: true
  when: ccp_fetch|default(true)

- name: Reset projects before patching
  shell: git reset --hard origin/master
  args:
    chdir: "{{ ccp_ms_root }}/{{ item.repo }}"
  run_once: true
  with_items: "{{ ccp_gerrit_reviews }}"
  when: ccp_gerrit_reviews|length > 0

- name: Patch projects
  shell: git fetch "{{ ccp_gerrit_base }}/{{ item.repo }}" {{ item.refspec }} && git cherry-pick FETCH_HEAD
  args:
    chdir: "{{ ccp_ms_root }}/{{ item.repo }}"
  run_once: true
  with_items: "{{ ccp_gerrit_reviews }}"
  when: ccp_gerrit_reviews|length > 0

- name: Build CCP images
  shell: "ccp --config-file={{ ccp_conf }} build >> /var/log/ccp-build.log 2>&1"
  run_once: true
  when: ccp_build|default(true)
