- name: Fetch CCP images
  shell: ccp --config-file={{ ccp_conf }} fetch
  run_once: true
  when: ccp_fetch|default(true)

- name: Reset projects before patching
  shell: git reset --hard origin/master
  args:
    chdir: "{{ ccp_ms_root }}/{{ item.repo }}"
  run_once: true
  with_items: "{{ ccp_gerrit_reviews }}"
  when: ccp_gerrit_reviews|length > 0

- name: Set some git config to enable patching on problem nodes
  shell: git config user.email "$USER@$HOSTNAME"
  args:
    chdir: "{{ ccp_ms_root }}/{{ item.repo }}"
  run_once: true
  with_items: "{{ ccp_gerrit_reviews }}"
  when: ccp_gerrit_reviews|length > 0

- name: Patch projects
  shell: git fetch "{{ ccp_gerrit_base }}/{{ item.repo }}" {{ item.refspec }} && git cherry-pick FETCH_HEAD
  args:
    chdir: "{{ ccp_ms_root }}/{{ item.repo }}"
  run_once: true
  with_items: "{{ ccp_gerrit_reviews }}"
  when: ccp_gerrit_reviews|length > 0

- name: Build default CCP images
  shell: "ccp --config-file={{ ccp_conf }} build"
  run_once: true
  when: ccp_build|default(true)

- name: Build additional CCP images
  shell: "ccp --config-file={{ ccp_conf }} build -c {{ item }}"
  run_once: true
  with_items: "{{ ccp_images }}"
  when: ccp_build|default(true)
