- name: Create dir
  file: path={{ ccp_misc_dir }} state=directory mode=0755

- name: Create ccp config
  template:
    src: ccp.yaml.j2
    dest: "{{ ccp_conf }}"
    owner: root
    group: root
    mode: 0600
